apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: myopenia
spec:
  type: ClusterIP
  selector:
    app: agent-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80