apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: myopenia
spec:
  type: ClusterIP
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80